---

apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cluster-autoscaler
  namespace: default
spec:
  interval: 5m
  releaseName: cluster-autoscaler
  chart:
    spec:
      chart: cluster-autoscaler
      sourceRef:
        kind: HelmRepository
        name: cluster-autoscaler
        namespace: default
      interval: 5m
  valuesFrom:
  - kind: Secret
    name: cluster-autoscaler
    valuesKey: autoDiscovery.clusterName
    targetPath: autoDiscovery.clusterName
  - kind: Secret
    name: cluster-autoscaler
    valuesKey: awsRegion
    targetPath: awsRegion
  targetNamespace: default
