---

apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cluster-autoscaler
  namespace: m-and-m
spec:
  interval: 5m
  releaseName: cluster-autoscaler
  chart:
    spec:
      chart: cluster-autoscaler
      sourceRef:
        kind: HelmRepository
        name: cluster-autoscaler
        namespace: m-and-m
      interval: 5m
  valuesFrom:
    - kind: ConfigMap
      name: cluster-autoscaler
  targetNamespace: m-and-m