---

apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: cluster-autoscaler
  namespace: m-and-m
spec:
  interval: 30s
  ref:
    branch: pierce/log-infra-via-flux
  url: https://github.com/DISHDevEx/napp

---

apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: loki-stack
  namespace: m-and-m
spec:
  interval: 30s
  ref:
    branch: pierce/log-infra-via-flux
  url: https://github.com/DISHDevEx/napp



---

apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: prom-stack
  namespace: m-and-m
spec:
  interval: 30s
  ref:
    branch: pierce/log-infra-via-flux
  url: https://github.com/DISHDevEx/napp

