---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: openverso
  namespace: default
spec:
  interval: 30s
  ref:
    branch: master
  url: https://github.com/DISHDevEx/openverso-charts
