apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: load-gen-global
subjects:
  - kind: ServiceAccount
    name: load-gen-serviceaccount
    namespace: default
roleRef:
  kind: ClusterRole
  name: load-gen-clusterrole
  apiGroup: rbac.authorization.k8s.io
