apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: traffic-sim-global
subjects:
  - kind: ServiceAccount
    metadata:
      name: traffic-sim
      namespace: default
      annotations:
        - authorization.k8s.io/impersonate: "false"",
        - services/status/patch: "[]"",
        - authorization.k8s.io/get: "[]""
  - kind: Node
    name: my-node
roleRef:
  kind: ClusterRole
  name: traffic-sim
  apiGroup: rbac.authorization.k8s.io
