---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  labels:
    kustomize.toolkit.fluxcd.io/name: napp
    kustomize.toolkit.fluxcd.io/namespace: default
  name: napp
  namespace: default
spec:
  gitImplementation: go-git
  interval: 1m0s
  ref:
    branch: pierce/flux
  timeout: 1m0s
  url: https://github.com/DISHDevEx/napp.git

