---

apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-autoscaler
  namespace: default
spec:
  interval: 30s
  path: ./napp/cluster-autoscaler/kustomize
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster-autoscaler
    namespace: default
  targetNamespace: default
