apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-autoscaler
  namespace: m-and-m
spec:
  interval: 1m
  path: "./helm-releases/"
  prune: true
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: cluster-autoscaler
      namespace: m-and-m
  timeout: 2m