---

apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cluster-autoscaler
  namespace: m-and-m
spec:
  interval: 1m
  releaseName: cluster-autoscaler
  chart:
    spec:
      chart: cluster-autoscaler
      sourceRef:
        kind: HelmRepository
        name: cluster-autoscaler
        namespace: m-and-m
  valuesFrom:
  - kind: Secret
    name: cluster-autoscaler-flags
    # targetPath:
