apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: openverso-custom-values
  namespace: openverso
spec:
  interval: 30s
  ref:
    branch: aakash/nuances-test
  url: https://github.com/DISHDevEx/napp

---

apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: gradiant-openverso-charts
  namespace: openverso
spec:
  interval: 30s
  ref:
    tag: open5gs-2.0.9
  url: https://github.com/Gradiant/openverso-charts

---

apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: cluster-autoscaler
  namespace: openverso
spec:
  interval: 1m
  url: https://kubernetes.github.io/autoscaler