apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: openverso-custom-values
  namespace: openverso
spec:
  interval: 30s
  ref:
    branch: agent-main
  url: https://github.com/DISHDevEx/napp

---

# apiVersion: source.toolkit.fluxcd.io/v1beta2
# kind: GitRepository
# metadata:
#   name: gradiant-openverso-charts
#   namespace: openverso
# spec:
#   interval: 30s
#   ref:
#     branch: master
#   url: https://github.com/Gradiant/openverso-charts

apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: gradiant-openverso-charts
  namespace: openverso
spec:
  interval: 30s
  ref:
    branch: master
  url: https://gradiant.github.io/openverso-charts/