apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
data:
  add_admin.sh: |-
{{ tpl (.Files.Get "resources/add_admin.sh") . | indent 4 }}