apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.fullname" . }}-s1ap
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if or .Values.services.s1ap.annotations .Values.commonAnnotations }}
  annotations:
    {{- if .Values.services.s1ap.annotations }}
    {{- include "common.tplvalues.render" (dict "value" .Values.services.s1ap.annotations "context" $) | nindent 4 }}
    {{- end }}
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  type: {{ .Values.services.s1ap.type }}
  {{- if .Values.services.s1ap.sessionAffinity }}
  sessionAffinity: {{ .Values.services.s1ap.sessionAffinity }}
  {{- end }}
  {{- if .Values.services.s1ap.sessionAffinityConfig }}
  sessionAffinityConfig: {{- include "common.tplvalues.render" (dict "value" .Values.services.s1ap.sessionAffinityConfig "context" $) | nindent 4 }}
  {{- end }}
  {{- if and .Values.services.s1ap.clusterIP (eq .Values.services.s1ap.type "ClusterIP") }}
  clusterIP: {{ .Values.services.s1ap.clusterIP }}
  {{- end }}
  {{- if (and (eq .Values.services.s1ap.type "LoadBalancer") (not (empty .Values.services.s1ap.loadBalancerIP))) }}
  loadBalancerIP: {{ .Values.services.s1ap.loadBalancerIP }}
  {{- end }}
  {{- if and (eq .Values.services.s1ap.type "LoadBalancer") .Values.services.s1ap.loadBalancerSourceRanges }}
  loadBalancerSourceRanges: {{- toYaml .Values.services.s1ap.loadBalancerSourceRanges | nindent 4 }}
  {{- end }}
  {{- if or (eq .Values.services.s1ap.type "LoadBalancer") (eq .Values.services.s1ap.type "NodePort") }}
  externalTrafficPolicy: {{ .Values.services.s1ap.externalTrafficPolicy | quote }}
  {{- end }}
  ports:
    - name: s1ap
      port: {{ .Values.services.s1ap.ports.s1ap }}
      targetPort: s1ap
      protocol: SCTP
      {{- if and (or (eq .Values.services.s1ap.type "NodePort") (eq .Values.services.s1ap.type "LoadBalancer")) (not (empty .Values.services.s1ap.nodePorts.s1ap)) }}
      nodePort: {{ .Values.services.s1ap.nodePorts.s1ap }}
      {{- else if eq .Values.services.s1ap.type "ClusterIP" }}
      nodePort: null
      {{- end }}
    {{- if .Values.services.s1ap.extraPorts }}
    {{- include "common.tplvalues.render" (dict "value" .Values.services.s1ap.extraPorts "context" $) | nindent 4 }}
    {{- end }}
  publishNotReadyAddresses: true
  selector: {{- include "common.labels.matchLabels" . | nindent 4 }}