apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - release.yaml
configMapGenerator:
  - name: custom-values
    files:
      - values.yaml=../5gSA_ues_values.yaml
configurations:
  - kustomizeconfig.yaml