apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - release.yaml
  - CA-release.yaml
  - open5gs_hpa_upf_custom.yaml
configMapGenerator:
  - name: custom-values
    files:
      - values.yaml=../5gSA_no_ues_values_with_nodegroups.yaml
#patches:
#  - target:
#       kind: HorizontalPodAutoscaler
#       namespace: openverso
#    path: open5gs_hpa_upf_custom.yaml

configurations:
  - kustomizeconfig.yaml