apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - release.yaml
configMapGenerator:
  - name: test-pierce
    files:
      - values.yaml=../test.yaml
configurations:
  - kustomizeconfig.yaml
