apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: open5gs
  namespace: openverso
spec:
  interval: 30s
  releaseName: open5gs
  chart:
    spec:
      chart: ./napp/charts/open5gs
      sourceRef:
        kind: GitRepository
        name: openverso-custom-values
        namespace: openverso
  valuesFrom:
    - kind: ConfigMap
      name: test.yaml
  targetNamespace: openverso
