apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: open5gs
  namespace: openverso
spec:
  interval: 30s
  releaseName: open5gs
  chart:
    spec:
      chart: ./charts/open5gs
      sourceRef:
        kind: GitRepository
        name: gradiant-openverso-charts
        namespace: openverso
  valuesFrom:
    - kind: ConfigMap
      name: custom-values
#  targetNamespace: openverso

---

  apiVersion: helm.toolkit.fluxcd.io/v2beta1
  kind: HelmRelease
  metadata:
    name: cluster-autoscaler
    namespace: m-and-m
    # this is where "flags" normally used with helm install should be placed metadata.annotations
    # example of how to structure the flag to annotation conversion at link below:
    # https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md
    # https://alicegg.tech/2020/11/09/helm.html
#    annotations:
#      "cluster-autoscaler.kubernetes.io/scale-down-unneeded-time": "600s"
  spec:
    interval: 1m
    releaseName: cluster-autoscaler
    chart:
      spec:
        #chart.spec.chart specifies the chart from the source to be deployed
        chart: cluster-autoscaler
        sourceRef:
          kind: HelmRepository
          name: cluster-autoscaler
          namespace: m-and-m
#    targetNamespace: m-and-m
