apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: open5gs
  namespace: openverso
spec:
  interval: 30s
  releaseName: open5gs
  chart:
    spec:
      chart: ./charts/open5gs
      version: 2.0.8
      sourceRef:
        kind: GitRepository
        name: gradiant-openverso-charts
        namespace: openverso
  valuesFrom:
    - kind: ConfigMap
      name: test-pierce
  targetNamespace: openverso
