# apiVersion: helm.toolkit.fluxcd.io/v2beta1
# kind: HelmRelease
# metadata:
#   name: open5gs
#   namespace: openverso
# spec:
#   releaseName: open5gs
#   chart:
#     spec:
#       chart: ./charts/open5gs
#       sourceRef:
#         kind: GitRepository
#         name: gradiant-openverso-charts
#         namespace: openverso
#       version: 2.0.8
#   interval: 30s
#   valuesFrom:
#     - kind: ConfigMap
#       name: test-pierce
#   targetNamespace: openverso

# ---

apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: open5gs
  namespace: openverso
spec:
  chart:
    spec:
      chart: ./charts/open5gs
      sourceRef:
        kind: HelmRepository
        name: gradiant-openverso-charts
      version: 2.0.8
  interval: 30s