---

apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: open5gs
  namespace: openverso
spec:
  interval: 30s
  releaseName: open5gs
  chart:
    spec:
      chart: ./charts/open5gs
      sourceRef:
        kind: GitRepository
        name: gradiant-openverso-charts
        namespace: openverso
  valuesFrom:
    - kind: ConfigMap
      name: custom-values
  targetNamespace: openverso

---

apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cluster-autoscaler
  namespace: openverso
spec:
  interval: 5m
  releaseName: cluster-autoscaler
  chart:
    spec:
      chart: cluster-autoscaler
      sourceRef:
        kind: HelmRepository
        name: cluster-autoscaler
        namespace: openverso
      interval: 5m
  valuesFrom:
  - kind: Secret
    name: cluster-autoscaler
    valuesKey: autoDiscovery.clusterName
    targetPath: autoDiscovery.clusterName
  - kind: Secret
    name: cluster-autoscaler
    valuesKey: awsRegion
    targetPath: awsRegion
  targetNamespace: openverso
