{{- if .Values.config.pcrf.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}-diameter
  labels: {{- include "common.labels.standard" . | nindent 4 }}
data:
  smf.conf: |
{{ tpl (.Files.Get "resources/config/diameter-smf.conf") . | indent 4 }}
{{- end }}