---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: openverso-master
  namespace: default
spec:
  interval: 30s
  ref:
    branch: master
  url: https://github.com/DISHDevEx/openverso-charts
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: openverso-matt
  namespace: default
spec:
  interval: 30s
  ref:
    branch: matt/gh_api_test
  url: https://github.com/DISHDevEx/openverso-charts
