---

apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prom-stack
  namespace: m-and-m
spec:
  interval: 5m
  releaseName: prom-stack
  chart:
    spec:
      chart: kube-prometheus
      sourceRef:
        kind: HelmRepository
        name: prom-stack
        namespace: m-and-m
      interval: 5m
  valuesFrom:
    - kind: ConfigMap
      name: prom-stack
  targetNamespace: m-and-m