---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: prometheus-storage-class
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp3
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: Immediate

---

apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prom-stack
  namespace: m-and-m
spec:
  interval: 5m
  releaseName: prom-stack
  chart:
    spec:
      chart: kube-prometheus
      sourceRef:
        kind: HelmRepository
        name: prom-stack
        namespace: m-and-m
      interval: 5m
  valuesFrom:
    - kind: ConfigMap
      name: prom-stack
  targetNamespace: m-and-m