apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}-diameter
  labels: {{- include "common.labels.standard" . | nindent 4 }}
data:
  hss.conf: |
{{ tpl (.Files.Get "resources/config/diameter-hss.conf") . | indent 4 }}
