---

apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: loki-stack
  namespace: m-and-m
spec:
  interval: 30s
  path: ./napp/Deployments/loki-stack/kustomize
  prune: true
  sourceRef:
    kind: GitRepository
    name: loki-stack
    namespace: m-and-m
  targetNamespace: m-and-m
