---

apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: open5gs
  namespace: openverso
spec:
  interval: 30s
  path: ./napp/Deployments/open5gs/kustomize
  prune: true
  sourceRef:
    kind: GitRepository
    name: openverso-custom-values
    namespace: openverso
  targetNamespace: openverso